import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <header className="bg-white shadow py-6">
        <h1 className="text-center text-3xl font-bold">Welcome to My Website</h1>
       
      </header>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased` }
      >
        <Navbar/>
        {children}
         <footer className="bg-blue-800 text-white text-center py-4 text-sm">
        &copy; 2025 My Website. All rights reserved.
      </footer>
      </body>
    </html>
  );
}
